version: '3'
services:
  nginx:
    image: nginx:alpine
    links:
      - env:env
      - node:node
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${LOCAL_PORT}:80
  node:
    image: "node:15.6.0-alpine"
    working_dir: /opt/front
    volumes:
      - ./front:/opt/front
      - /opt/front/node_modules
    entrypoint: "/bin/sh -c 'npm install && npm run dev'"
  env:
    image: "golang:1.15"
    environment:
      - GO111MODULE=on
      - DATASTORE_EMULATOR_HOST=datastore:8059
      - DATASTORE_PROJECT_ID=local-app
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - PORT=8080
    working_dir: /opt/app
    volumes:
      - ./server:/opt/app
    links:
      - datastore:datastore
    command: /bin/sh -c 'go mod download && go run -mod=vendor .'

  datastore:
    image: google/cloud-sdk
    environment:
      - PROJECT_ID=local-app
    command: /bin/bash -c "gcloud beta emulators datastore start --host-port 0.0.0.0:8059 --project $$PROJECT_ID --data-dir /data"
    ports:
      - 8059:8059
    volumes:
      - datastore_volume:/data
volumes:
  datastore_volume:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/16
